# Site settings
title: Integer Linear Programming for Natural Language Processing
description: > # this means to ignore newlines until "baseurl:"
  Constrained Conditional Models: Modeling natural language processing inference as integer linear programs

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
